baseURL = 'https://jimenezgomez.org/'
languageCode = 'es'
title = 'Francisco Javier Jim√©nez G√≥mez'
theme = 'stack'
copyright = 'Francisco Javier Jim√©nez G√≥mez'

[params]
  mainSections = ['posts']
  rssFullContent = true
  favicon = '/img/favicon.ico'
  # Homepage layout
  homepageLayout = 'portfolio'

  # Sidebar configuration
  [params.sidebar]
    emoji = 'üíª'
    subtitle = 'Software Architecture & Open Source'
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = 'img/avatar.png'

  # Footer
  [params.footer]
    since = 2020
    customText = ''

  # Date format
  [params.dateFormat]
    published = 'Jan 02, 2006'
    lastUpdated = 'Jan 02, 2006 15:04 MST'

[params.article]
    showCover = false
    math = false
    toc = true
    readingTime = true
    [params.article.license]
      enabled = true
      default = 'Licensed under CC BY-NC-SA 4.0'

# Widgets en la p√°gina principal
[[params.widgets.homepage]]
  type = 'search'

[[params.widgets.homepage]]
  type = 'archives'
  [params.widgets.homepage.params]
    limit = 5

[[params.widgets.homepage]]
  type = 'categories'
  [params.widgets.homepage.params]
    limit = 10

[[params.widgets.homepage]]
  type = 'tag-cloud'
  [params.widgets.homepage.params]
    limit = 10

[[params.widgets.page]]
  type = 'toc'

# Enlaces sociales
[[menu.social]]
  identifier = 'github'
  name = 'GitHub'
  url = 'https://github.com/javi-jimenez'
  [menu.social.params]
    icon = 'brand-github'

[[menu.social]]
  identifier = 'twitter'
  name = 'Twitter'
  url = 'https://twitter.com/Lubok9'
  [menu.social.params]
    icon = 'brand-twitter'

[[menu.social]]
  identifier = 'linkedin'
  name = 'LinkedIn'
  url = 'https://linkedin.com/in/ximenezfrancisco'
  [menu.social.params]
    icon = 'brand-linkedin'

# Men√∫ principal (opcional)
[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true

